### PR TITLE
[QT] Add Pool Picker

### PR DESCRIPTION
**Pull request by alamshafil**
This PR adds a pool picker to quickly help new miners on what arguments to use. As of right now it's in WIP and low priority. 
Any feedback on UI design or code is greatly appreciated.

### CODE REVIEW

**Comment by fdoving** [comment]
Personally I don't think this feature belongs in core.
I think it is better to have something like this as part of the website, some discord bot or similar external tools.

**Comment by primitt** [comment]
> Personally I don't think this feature belongs in core.
> 
> I think it is better to have something like this as part of the website, some discord bot or similar external tools.

Hey! Im the maintainer of this pool picker over at aviannetwork/AvianPoolPicker repo. I have an external EXE there that you can use. I personally like this feature in the core wallet as it makes it less like a cookie cutter for professional users, but a custom wallet for all to use. Its nice to have everything in one place instead of looking for things in 90 different places.

Thanks,
Priansh Mittra or ayonull

**Comment by fdoving** [comment]
> > Personally I don't think this feature belongs in core.
> > I think it is better to have something like this as part of the website, some discord bot or similar external tools.
> 
> Hey! Im the maintainer of this pool picker over at aviannetwork/AvianPoolPicker repo. I have an external EXE there that you can use. I personally like this feature in the core wallet as it makes it less like a cookie cutter for professional users, but a custom wallet for all to use. Its nice to have everything in one place instead of looking for things in 90 different places.
> 
> Thanks, Priansh Mittra or ayonull

Anything pulling things from the web inside core is a potential security risk in my opinion. Core is a wallet. If you don't pull updated pool-lists from the web you need new releases to update, it will be out-dated in weeks.

New users are most likely already visiting the website to download core, clicking on a link there makes more sense to me. If you want the feature in core, you can make a button to open the website at that url and get around most of the potential security issues. (With a warning that you are now about to open URL in your default browser etc.. ) 

The feature is most likely not something users need daily or weekly. 
This can be a website one can open with a click from the wallet, a click from discord, twitter, reddit or the already existing website.

**Comment by alamshafil** [comment]
I also agree that pulling anything from the web could pose a security risk which is why I thought of putting a warning on the dialog to inform the user, but thinking about it makes sense for a new user to click on a website link since this feature is most likely to be used once. I was also worried about the pool list going down or not being updated. It makes more sense to put a link to a site with a warning. I'll most likely go ahead and add a link in the Core wallet. I opened this pull request to get feedback and see what others thought about this idea. Thank you for the feedback! I'll talk with the team and see what they think abut it.

Additionally we could include the pool-picker tool in the `contrib` folder.

**Comment by alamshafil** [comment]
Thinking about it, the Ravencoin Core wallet already grabs the price from an external API. Which means the pool picker could be included, but I think it's best to leave as it link to external website since this is most likely going to be used once.

**Comment by primitt** [comment]
Sure! We can possibly make it open an external app.

**Comment by primitt** [comment]
But do think abt what furious said above

**Comment by alamshafil** [comment]
Closed in favor of adding to v4.0.0

**Pull request closed without merging**
